# Generated by Django 5.2.1 on 2025-05-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="food_images/"),
                ),
                (
                    "health_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Saludable", "Saludable"),
                            ("Aceptable", "Aceptable"),
                            ("Poco Saludable", "Poco Saludable"),
                            ("No Saludable", "No Saludable"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("overall_confidence_score", models.FloatField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "overall_nova_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Alimentos sin procesar o mínimamente procesados",
                                "Alimentos sin procesar o mínimamente procesados",
                            ),
                            (
                                "Ingredientes culinarios procesados",
                                "Ingredientes culinarios procesados",
                            ),
                            ("Alimentos procesados", "Alimentos procesados"),
                            (
                                "Alimentos y bebidas ultraprocesados",
                                "Alimentos y bebidas ultraprocesados",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Análisis de Alimento",
                "verbose_name_plural": "Análisis de Alimentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "nova_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Alimentos sin procesar o mínimamente procesados",
                                "Alimentos sin procesar o mínimamente procesados",
                            ),
                            (
                                "Ingredientes culinarios procesados",
                                "Ingredientes culinarios procesados",
                            ),
                            ("Alimentos procesados", "Alimentos procesados"),
                            (
                                "Alimentos y bebidas ultraprocesados",
                                "Alimentos y bebidas ultraprocesados",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "food_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="food_analyzer_api.foodanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstimatedVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("ml", "ml"), ("gr", "gr")], max_length=5
                    ),
                ),
                (
                    "food_analysis",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overall_estimated_volume",
                        to="food_analyzer_api.foodanalysis",
                    ),
                ),
                (
                    "ingredient",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimated_volume",
                        to="food_analyzer_api.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("kcal", "kcal")], default="kcal", max_length=10
                    ),
                ),
                (
                    "ingredient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calories",
                        to="food_analyzer_api.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Macros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protein", models.FloatField()),
                ("carbohydrates", models.FloatField()),
                ("fat", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("gr", "gr")], default="gr", max_length=5
                    ),
                ),
                (
                    "ingredient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macros",
                        to="food_analyzer_api.ingredient",
                    ),
                ),
            ],
        ),
    ]
